### ISSUE TITLE
Suggestion: Using the single .env file for simplicity

### ISSUE THREAD

**Issue by ajhalili2006** [marcomelilli/gatsby-firebase-simple-auth#1]
Using the single `.env` file can save time, the only thing is adding either `_DEV` or `_PRODUCTION` suffix. This way, developers who use and fork your starter can use only one `.env` file, they just needed to add some flags or suffixes to know which secrets should be used based on the type of deployment.

```sh
## Production-ready secrets
GATSBY_FIREBASE_API_KEY_PRODUCTION=<YOUR_FIREBASE_API_KEY>
GATSBY_FIREBASE_AUTH_DOMAIN_PRODUCTION=<YOUR_FIREBASE_AUTH_DOMAIN>
GATSBY_FIREBASE_DATABASE_URL_PRODUCTION=<YOUR_FIREBASE_DATABASE_URL>
GATSBY_FIREBASE_PROJECT_ID_PRODUCTION=<YOUR_FIREBASE_PROJECT_ID>
GATSBY_FIREBASE_STORAGE_BUCKET_PRODUCTION=<YOUR_FIREBASE_STORAGE_BUCKET>
GATSBY_FIREBASE_MESSAGING_SENDER_ID_PRODUCTION=<YOUR_FIREBASE_MESSAGING_SENDER_ID>
GATSBY_FIREBASE_APP_ID_PRODUCTION=<YOUR_FIREBASE_APP_ID>
GATSBY_FIREBASE_MEASUREMENT_ID_PRODUCTION=<YOUR_FIREBASE_ANALYTICS_TRACKING_ID>

## Development secrets
GATSBY_FIREBASE_API_KEY_DEV=<YOUR_FIREBASE_API_KEY>
GATSBY_FIREBASE_AUTH_DOMAIN_DEV=<YOUR_FIREBASE_AUTH_DOMAIN>
GATSBY_FIREBASE_DATABASE_URL_DEV=<YOUR_FIREBASE_DATABASE_URL>
GATSBY_FIREBASE_PROJECT_ID_DEV=<YOUR_FIREBASE_PROJECT_ID>
GATSBY_FIREBASE_STORAGE_BUCKET_DEV=<YOUR_FIREBASE_STORAGE_BUCKET>
GATSBY_FIREBASE_MESSAGING_SENDER_ID_DEV=<YOUR_FIREBASE_MESSAGING_SENDER_ID>
GATSBY_FIREBASE_APP_ID_DEV=<YOUR_FIREBASE_APP_ID>
GATSBY_FIREBASE_MEASUREMENT_ID_DEV=<YOUR_FIREBASE_ANALYTICS_TRACKING_ID>

## Flag to use dev secrets instead: Set to true to continue
USE_DEV_SECRETS_ON_PROD=true

## Flag to use prod secrets on dev servers: Set true to continue.
## When both of these flags are enabled, they'll be used based on what deployment type does an dev used.
USE_PROD_SECRETS_ON_DEV=true
```

**Comment by marcomelilli** [comment]
Hi! Thank you for the suggestion. Why do you think one file is better than two (.develop and .production)? I followed gatsby doc for best practices: https://www.gatsbyjs.org/docs/environment-variables/#client-side-javascript
I didn't commit these files because they are in the gitignore and I wanted to avoid that people will fork the project and they will commit their secrets in the repository

**Comment by ajhalili2006** [comment]
Okay, I read the docs. So, did I need to add `NODE_ENV` variable to `production`, `test`, or `staging` if I want to just one `.env` file?

**Comment by marcomelilli** [comment]
In the gatsby-config.js you can see:
```
require("dotenv").config({
  path: `.env.${process.env.NODE_ENV}`,
})
```
And it works in this way with more `.env` files:

> 
> By default gatsby supports only 2 environments:
> 
> If you run gatsby develop, then you will be in the ‘development’ environment.
> If you run gatsby build or gatsby serve, then you will be in the ‘production’ environment.
> 



I don't know if it's possible use only  a `.env` file, maybe you can change gatsby-config in this way:
```
require("dotenv").config({
  path: `.env`,
})
```


If you want add more custom environment (for example ".env.staging") you can't override NODE_ENV variable but you have to use another variable: https://www.gatsbyjs.org/docs/environment-variables/#additional-environments-staging-test-etc

```
const activeEnv =
  process.env.GATSBY_ACTIVE_ENV || process.env.NODE_ENV || "development"
require("dotenv").config({
  path: `.env.${activeEnv}`,
})
```
and build in this way from shell: `GATSBY_ACTIVE_ENV=staging npm run develop`

I understand you think one file is better, but this way is not bad too :)
