### ISSUE TITLE
Can't sign with Google in the demo

### ISSUE THREAD

**Issue by dandv** [marcomelilli/gatsby-firebase-simple-auth#2]
This domain (gatsby-firebase-simple-auth.netlify.app) is not authorized to run this operation. Add it to the OAuth redirect domains list in the Firebase console -> Auth section -> Sign in method tab.  Dismiss

![image](https://user-images.githubusercontent.com/33569/80301089-1dce8600-87f6-11ea-8a02-3fa24d364600.png)

**Comment by marcomelilli** [comment]
Netlify moved all the sites (without a custom domain) from .com to .app
I just fixed it, thank you🙂

**Comment by dandv** [comment]
Ah, that explains why [the other Gatsby-Firebase theme](https://github.com/epilande/gatsby-theme-firebase/issues/230) is also broken :)

Thanks for the quick fix!

BTW, any chance to [add Apple sign in](https://github.com/epilande/gatsby-theme-firebase/issues/231) support?

**Comment by marcomelilli** [comment]
Yes you can already enable it. In this starter I used react-firebaseui that is a wrapper of [firebaseui-web](https://github.com/firebase/firebaseui-web/#available-providers).
You just need to add the Apple authentication provider in the signin options in the Login component [here](https://github.com/marcomelilli/gatsby-firebase-simple-auth/blob/607a427888bf8c84e4d2f3b4edcdb141140517e8/src/components/Login.jsx#L23)

**Comment by dandv** [comment]
Ah... firebaseui-web is so slow it's is the only reason I prefer Auth0 over Firebase. It's not only due to the [huge bundle size](https://github.com/firebase/firebase-js-sdk/issues/332#issuecomment-423402372), it's just [SLOW](https://github.com/firebase/firebaseui-web/issues/436#issuecomment-501816209). Like 5x slower than hand-coded social login, and 3x slower than Auth0.

I was hoping the theme was using Firebase Auth directly under the hood, but I know that's not trivial.

**Comment by marcomelilli** [comment]
@dandv yes you're right, it's very slow.. but it's very easy to implement. Maybe one day I will migrate to Firebase Auth directly. 
Ps: I'd like to try Auth0 but it too expensive imo
