### ISSUE TITLE
Back functionality doesn't work after clicking Profile

### ISSUE THREAD

**Issue by dandv** [marcomelilli/gatsby-firebase-simple-auth#3]
1. Go to https://gatsby-firebase-simple-auth.netlify.app
2. Click ["Go to your profile"](https://gatsby-firebase-simple-auth.netlify.app/app/profile)
3. Click the back button in Chrome.

The route will stay at https://gatsby-firebase-simple-auth.netlify.app/app/login.

**Comment by marcomelilli** [comment]
Thanks fixed
