### ISSUE TITLE
Apple login example

### ISSUE THREAD

**Issue by dandv** [marcomelilli/gatsby-firebase-simple-auth#4]
Would be reassuring to see this working, because I tried [adding Apple](https://github.com/epilande/gatsby-theme-firebase/issues/231) to @epilande's theme [in this file](https://github.com/epilande/gatsby-theme-firebase/blob/master/gatsby-theme-firebase/src/firebase/auth/index.ts) but it turned out that `firebase.auth.AppleAuthProvider()` doesn't exist.

**Comment by marcomelilli** [comment]
In Login.jsx try:
```
  signInOptions: [
        auth.GoogleAuthProvider.PROVIDER_ID,
        auth.EmailAuthProvider.PROVIDER_ID,
        "apple.com"
    ],
```
It seems to work
