### ISSUE TITLE
Add .env.sample + firebase steps required for smoother Dev experience

### ISSUE THREAD

**Issue by ThomasJanUta** [marcomelilli/gatsby-firebase-simple-auth#5]
Great starter. It does exactly one thing and it works.

I had minor problems getting started because I had barely any firebase experience. I propose the following changes to enable a smooth dev experience:

- Add `.env.sample` with sample environment variables
- Add `Getting firebase up and running` into the README
  - inclues how to set up a project or at least a link to the official docs
  - includes that you have to enable email and google authentication in firebase
  - includes that you have to enable a web project and paste the credentials into the .env.sample in firebase

These links helped me and should be added to the README:
- https://firebase.google.com/docs/web/setup
- https://firebase.google.com/docs/projects/learn-more
- https://firebase.google.com/docs/auth

Should I go ahead and make a pull request?

**Comment by marcomelilli** [comment]
Hi Thomas, yes please. Pull requests that improve the starter and the doc are always welcome :)
