### ISSUE TITLE
Trouble with gatsby-plugin-firebase v0.2

### ISSUE THREAD

**Issue by masjugo** [marcomelilli/gatsby-firebase-simple-auth#7]
Hi Marco. 
your gatsby starter looks really useful and works just fine, however I'm using it to learn how authentication works with firebase and gatsby. I'm trying to update the use of **gatsby-plugin-firebase** to the v0.2 (using _useEffect_ instead of _useFirebase_ in the login component) but the browser returns this error in .../app/login:

> `TypeError: gatsby_plugin_firebase__WEBPACK_IMPORTED_MODULE_5__.default.database is not a function`

It seems like I need to create a react context to use firebase functions, but I don't really understand how it would work in your starter.
I hope you can help me, maybe this plugin update usage could be a nice upgrade to your starter.
Thanks!

--
note: I'm a designer learning how to code so I apologize if this is not the kind of issue you were expecting.

**Comment by marcomelilli** [comment]
Hi! I just upgraded the starter with the new gatsby-plugin-firebase v0.2 . Let me know if everything is ok :)
